//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSPruebaTecnicaAND.Models.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PruebaTecnicaANDEntities : DbContext
    {
        public PruebaTecnicaANDEntities()
            : base("name=PruebaTecnicaANDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cuentanos> Cuentanos { get; set; }
        public virtual DbSet<Opinion> Opinion { get; set; }
        public virtual DbSet<OtrosTemas> OtrosTemas { get; set; }
        public virtual DbSet<Tramites> Tramites { get; set; }
    
        public virtual ObjectResult<SP_LIST_TRAMITES_Result> SP_LIST_TRAMITES()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_LIST_TRAMITES_Result>("SP_LIST_TRAMITES");
        }
    
        public virtual ObjectResult<SP_LIST_CUENTANOS_Result> SP_LIST_CUENTANOS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_LIST_CUENTANOS_Result>("SP_LIST_CUENTANOS");
        }
    
        public virtual ObjectResult<SP_LIST_OPINION_Result> SP_LIST_OPINION()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_LIST_OPINION_Result>("SP_LIST_OPINION");
        }
    
        public virtual ObjectResult<SP_LIST_OTROSTEMAS_Result> SP_LIST_OTROSTEMAS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_LIST_OTROSTEMAS_Result>("SP_LIST_OTROSTEMAS");
        }
    }
}
