//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSPruebaTecnicaAND.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Opinion
    {
        public int id { get; set; }
        public int estado { get; set; }
        public string nombre { get; set; }
        public string entidad { get; set; }
    }
}
